name: Best Food Tour.com
favicon: null
layout_spectrum: 0.50188
typography_spectrum: 0.46634
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c0392b'
    - '#ffffff'
    - '#909090'
    - '#c7c7c7'
  brandStrength: 0.03569144103676081
  lightness: 0.656360229011625
  saturation: 0.12313741445541382
  rhythmicContrast: 0.09131093858741224
purpose: []
