name: Best Food Tour.com
favicon: null
layout_spectrum: 0.4097395509015769
typography_spectrum: 0.5819749373476952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.03569144103676081
  lightness: 0.656360229011625
  saturation: 0.12313741445541382
  rhythmicContrast: 0.09131093858741224
purpose: []
